// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-HK_VEkiJbsmnRcQ1GMp3l3TjMnvzWOE',
    appId: '1:283455709596:web:d97673cf66c5e36f59e859',
    messagingSenderId: '283455709596',
    projectId: 'onebarangay-de3cd',
    authDomain: 'onebarangay-de3cd.firebaseapp.com',
    storageBucket: 'onebarangay-de3cd.firebasestorage.app',
    measurementId: 'G-JNLD3KSW57',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa5qIaU8z8uIKwkSNqun9DRbAqLo9ahbc',
    appId: '1:283455709596:android:fb9e8080b1ebeb9c59e859',
    messagingSenderId: '283455709596',
    projectId: 'onebarangay-de3cd',
    storageBucket: 'onebarangay-de3cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzvw_Eg0UwWljfqQX9fK-sND2nCDaPoSI',
    appId: '1:283455709596:ios:c84bf1bfdb29717559e859',
    messagingSenderId: '283455709596',
    projectId: 'onebarangay-de3cd',
    storageBucket: 'onebarangay-de3cd.firebasestorage.app',
    iosBundleId: 'com.example.oneBarangay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzvw_Eg0UwWljfqQX9fK-sND2nCDaPoSI',
    appId: '1:283455709596:ios:c84bf1bfdb29717559e859',
    messagingSenderId: '283455709596',
    projectId: 'onebarangay-de3cd',
    storageBucket: 'onebarangay-de3cd.firebasestorage.app',
    iosBundleId: 'com.example.oneBarangay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-HK_VEkiJbsmnRcQ1GMp3l3TjMnvzWOE',
    appId: '1:283455709596:web:a1bfedde645d481559e859',
    messagingSenderId: '283455709596',
    projectId: 'onebarangay-de3cd',
    authDomain: 'onebarangay-de3cd.firebaseapp.com',
    storageBucket: 'onebarangay-de3cd.firebasestorage.app',
    measurementId: 'G-VSGKY2Z75S',
  );
}
